apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  - name: PostgreSQL - Warehouse
    type: postgres
    access: proxy
    uid: pg-warehouse
    url: postgres:5432
    database: dataair
    user: dataair
    isDefault: false
    editable: true
    secureJsonData:
      password: ${POSTGRES_PASSWORD}

  - name: Redis
    type: redis
    access: proxy
    uid: redis
    url: redis://redis:6379
    editable: true
